language: ruby
script: bundle exec rspec
rvm:
- 2.6.3
deploy:
  provider: heroku
  api_key:
    secure: D2KppULBAxOSABKBT1N8+jPG2Ye+vfpAut8P/mf8uLGX1DdoV3Me5yxRFfPGTKB56EuPdKbQ9NoLsAOLGiLIt5dmH02KsQLcqsyYpeFXqWjH/0M4wNgPt+pyJLtS2pBolLqpVfujkt8JAj19l8quVREyi0a8qowpbJjukToJKcWemPigNY7E94tZx5QS8+mHz/98hwX6q2rpnBVm15W6ng1JQUScxdpnGQuiWcrDoLh3LZ9THXgGlbtYrH3CqPx06NAC2M7SrDKnl0nfnmvgtZBIPT/5hni5lSsJV0KUjQhHLUwwlCPbxLdU8FT7/1rfe0WHkCQT7Vz51m1VIHF0Jcm3nf0s9CpeO5fgJEXC1YfNSMX60VSUaPdyV8UAGC0IDSwzA9G2oAmf+sEx9ZLKjwj7sdvRufizQP0+3jfcMjg690glG6z6FkOpPTXVdI7r+qJu1rPbPUhYhbb3MX7J1rfjq/tbOedbedIxGbMihr0OpNzCeadEyzT90iNgPDh+tw0BbjUmh9zZtjj9+8Rjq+P7GKj9GsRResOshnhqrcQfsynliVDKNyUL2DNi/KQqiBOrU829o7jfuwnpM3VytWJXHw/BuqiHO64+TmhR3BT5ozOAY7lPsCNbC7TnNOeG681u25jbm2J8n8OA4M2aVRSjNTrx0jzvNufg/aQ1Lic=
  app: tranquil-meadow-17161
  on: 
    repo: ben-d758/mumbling_kata